src/models.py

added conditions listed in issue #4367

added conditions for literature tab

---

src/models.py

Bug fixes: 
1. Display issue: code needs to remove underscores from GO.display_name for the 3 root terms ('molecular_function', 'biological_process', 'cellular_component'
2. GO evidence codes need to link to Gene Ontology wiki reference page, not BioPortal - GO evidence code urls added to ECO_URL

4477 Bug Fixes

---

scripts/search/es_mapping.py
scripts/search/index_elastic_search.py
scripts/search/mapping.py
src/models.py
src/search_helpers.py
src/views.py
test/mock_helpers.py

- changed mappings to include aliases object
- fixed go tab wiki refs to point to GO urls instead of bio-portal refs
- added aliases to elastic-search json_response object that's used to set is_quick flag

4487 es issues and other bugs

---

scripts/search/index_elastic_search.py
scripts/search/not_mapped.json

-Added not_mapped index method
-Added not_mapped genes file that contain data to be indexed

4590 not mapped genes

---

src/models.py
src/models_helpers.py
src/views_colleagues.py

4625 colleague info

---

src/models.py

@ragingsquirrel3 made minor change.

minor bug fix, undefined variable

---

schema/nex2-annotation-tables.sql
schema/nex2-constraints.sql
schema/nex2-object-tables.sql
schema/nex2-object-triggers.sql

There are some RESERVEDNAME changes included in this pull request in the files nex2-object-tables.sql and nex2-object-triggers.sql.  These were committed, but not pushed before the 4761 brance was made.  I'll make a new branch for the remaining RESERVEDNAME schema changes.

4761 dnasubsequence

---

src/loading/promote_reference_triage.py

Code changes for addressing the issues mentioned in the following Redmine items - 
1. http://redmine.stanford.edu/issues/4790
2. http://redmine.stanford.edu/issues/4787
3. http://redmine.stanford.edu/issues/4759

Promote ref triage

---

scripts/search/index_elastic_search.py

http://redmine.stanford.edu/issues/4821

4821 modify es behavior

---

scripts/search/index_elastic_search.py

http://redmine.stanford.edu/issues/4847

Facilitate acceptance of Alliance SGDID in quick search

---

reference_title_citation_update.py
scripts/loading/reference/promote_reference_triage.py
scripts/loading/reference/pubmed.py
scripts/loading/reference/reference_title_citation_update.py
scripts/loading/reference/reference_update.py

Fixes to get around with BioPython bug for text with html tags.

Citations 4942

---

src/views.py

allow lowercase input; check only name or seq is provided; check product size cannot be less than target size

few input checks

---

scripts/dumping/curation/dump_go_annotations.py
scripts/loading/locus/addStdGeneName.py
scripts/loading/locus/standardizeReservedName.py

This request includes the following:
1. fix to dbentity_status issue for GAP dumping script
2. new script for adding a standard gene name to an ORF
3. some minor fixes to reserved gene name standardization.

Dbentity status4911

---

schema/nex2-ontology-tables.sql
schema/nex2-ontology-triggers.sql
src/__init__.py
src/models.py
src/views.py

https://redmine.yeastgenome.org/issues/4624

4624 genomesnapshot

---

scripts/search/index_elastic_search.py

Adding code to index complex data

adding complex to es

---

src/models.py

add edges to disease network directly from yeast gene to disease

5109dis network

---

.travis.yml
src/models.py

https://redmine.yeastgenome.org/issues/5171

Hotfix for 5171 and config change for Travis CI build failures

---

schema/nex2-object-triggers.sql

fix orcid delete datatype from integer to varchar
can this be merged into master?

fix orcid delete datatype from integer to varchar

---

system_config/nginx/sites-available/sgd-web
system_config/varnish.vcl

Looking to merge the nginx and varnish configs into qa (and eventually master).  But since I haven't done PRs before, please let me know if you need me to do anything more or need additional information.  Thanks!

5154 nginx varnish configs

---

requirements.txt

Update PyOpenSSL package to remove security vulnerabilities reported by Github

Update PyOpenSSL package

---

reference_title_citation_update.py
schema/nex2-object-triggers.sql
scripts/loading/load_reference_triage.py
scripts/loading/reference/add_reference.py
scripts/loading/reference/promote_reference_triage.py
scripts/loading/reference/promote_reference_triage_from_file.py
scripts/loading/reference/reference_title_citation_update.py
scripts/loading/reference/reference_triage.py
scripts/loading/reference/reference_update.py
scripts/loading/reference/reference_url_update.py
src/loading/promote_reference_triage.py

PR from #47 
--
Merging to develop branch for testing before moving to prod.

Katrinleinweber resolve do is securely

---

scripts/dumping/curation/dump_go_annotations.py
scripts/dumping/curation/dump_go_annotations_not_in_gpad.py
scripts/loading/complex/load_complex.py
scripts/loading/complex/load_complexbindingannotation.py
scripts/loading/files/load_filedbentities.py
scripts/loading/ontology/efo.py
scripts/loading/protein/data/ReadME.md
scripts/loading/protein/load_abundance_data-29361465.py
scripts/loading/protein/logs/ReadME.md
scripts/loading/protein/preprocess_abundance_data-29361465.py
src/__init__.py
src/models.py
src/views.py

new/updated code for loading data.

Sw oct 2018

---

src/curation_views.py
src/helpers.py
src/loading/load_summaries_sync.py
src/tsv_parser.py

- Enable more summary types upload

5047 new summary types

---

Makefile
package-lock.json
src/loading/scrapy/pages/spiders/pages_spider.py

- Added timestamp for site crawling script

added log format

---

src/models.py

Fixed to use date_assigned for computational annotations.

fixed to use date_assigned for computational annotations

---

src/__init__.py
src/views.py

Adding new endpoint for retrieving go slim terms

adding new endpoint to get goslim terms

---

system_config/nginx/sites-available/sgd-web

Add upstream timing info to logs.

5290_nginx_add_timing_info

---

scripts/loading/util.py

https://redmine.yeastgenome.org/issues/5288
Update the script to check for number and numbers with P to not link to chromosome pages.

Updated to check words (integers) with 'P' to not link chromosome page.

---

scripts/search/index_elastic_search.py
scripts/search/mapping.py
src/views.py

I am not sure all the changes are required. Please check carefully that it doesn't break anything. For e.g.  json_response_fields  (here do I need to change from go_loci to gene_ontology_loci ?)
https://redmine.yeastgenome.org/issues/5303

5122doloci

---

src/__init__.py
src/curation_views.py
src/helpers.py
src/js_src/containers/curateHome/layout.js
src/js_src/containers/newsLetter/index.js
src/js_src/containers/newsLetter/style.css
src/js_src/routes.js
src/models_helpers.py
src/views.py

https://redmine.yeastgenome.org/issues/5174

5174 news letter

---

src/__init__.py
src/curation_helpers.py
src/curation_views.py
src/helpers.py
src/js_src/actions/ptmActions.js
src/js_src/components/dataList.js
src/js_src/components/style.css
src/js_src/containers/curateHome/layout.js
src/js_src/containers/postTraslationModificaition/fileupload.js
src/js_src/containers/postTraslationModificaition/index.js
src/js_src/containers/postTraslationModificaition/ptmForm.js
src/js_src/reducers/index.js
src/js_src/reducers/ptmReducer.js
src/models.py
src/models_helpers.py
src/views.py

https://redmine.yeastgenome.org/issues/5327

5327 post translational modification

---

scripts/loading/dbxref/update_pantherids.py

https://redmine.yeastgenome.org/issues/5268

5268 add panther ids to db

---

src/js_src/components/dataList.js

https://redmine.yeastgenome.org/issues/5390

add setNewValue prop for new values

---

scripts/search/index_elastic_search.py
scripts/search/index_es_helpers.py
scripts/search/mapping.py
src/views.py
test/fixtures.py
test/mock_helpers.py

https://redmine.yeastgenome.org/issues/5369

5369 add chemical to search

---

test/test_views/test_chemical.py

adding more tests for chemical page:
1. chemical_go_details
2. chemical_complex_details
3. chemical_network_graph

adding more tests for chemical page: go, complex, & graph

---

test/fixtures.py
test/mock_helpers.py
test/test_views/test_complex.py

added unit test code for complex page to test/fixtures.py & test/mock_helpers.py
added new file: test/test_views/test_complex.py

adding unit test code for complex page

---

src/curation_views.py
test/fixtures.py
test/mock_helpers.py
test/test_curation/test_curation_views.py

https://redmine.yeastgenome.org/issues/5408

5408 test curation interface

---

src/views.py
test/fixtures.py
test/mock_helpers.py
test/test_views/test_locus.py

https://redmine.yeastgenome.org/issues/5400

5400 locus tests

---

requirements.txt
scripts/disambiguation/index_disambiguation.py
scripts/loading/biogrid/geninteractionannotation2.py
scripts/loading/load_reference_triage.py
scripts/loading/reference/add_reference.py
scripts/loading/reference/pubmed.py
scripts/loading/reference/reference_display_name_update.py
scripts/loading/reference/reference_update.py
scripts/search/index_elastic_search.py
src/loading/promote_reference_triage.py

https://redmine.yeastgenome.org/issues/5433

Python3 loading scripts

---

src/js_src/containers/layout/index.js
src/js_src/routes.js

https://redmine.yeastgenome.org/issues/5467

Move CI routes into layout and keep public routes in routes.js

---

src/helpers.py

https://redmine.yeastgenome.org/issues/5470

Update translate method to delete spl characters.

---

src/curation_views.py

https://redmine.yeastgenome.org/issues/5472

Add checks to verify index as number and residue as single character.

---

src/curation_views.py
src/helpers.py
src/js_src/containers/newsLetter/newsletterform.js

https://redmine.yeastgenome.org/issues/5473
Fixed the UI to display message to user for newsletter interface.

5473 newsletter ui

---

src/js_src/containers/layout/index.js
src/js_src/containers/newsLetter/newsletterform.js

https://redmine.yeastgenome.org/issues/5476

Move the routes /reservations to one switch.

---

src/js_src/components/deleteButton.js
src/js_src/containers/colleagues/show.js
src/js_src/containers/layout/index.js
src/js_src/containers/reserve/show.js
src/js_src/routes.js

https://redmine.yeastgenome.org/issues/5483

5483 fix routes

---

src/curation_views.py

https://redmine.yeastgenome.org/issues/5482

5482 regulation error message

---

requirements.txt
templates/home.jinja2

https://redmine.yeastgenome.org/issues/5491

5491 fix hot reloading

---

src/curation_views.py

https://redmine.yeastgenome.org/issues/5450
Fixing issue of date_last_modified for colleague.

Add value for date_last_modified for colleague

---

src/js_src/components/annotationSummary.js
src/loading/load_summaries_sync.py
src/models.py

- Enable timestamp for curator activity

5501 timestamp fix

---

src/js_src/containers/curateLit/litConstants.js
src/models.py

Fixed 'other primary literature tag bug' in literature triaging interface.

Triage 5503

---

src/models.py

Fixed to handle 'other_primary tag' properly.

fixed to handle other_primary tag properly

---

scripts/dumping/ncbi/dump_tbl_files.py

Fixing NCBI asn1 files formatting issues

fixed several formating issues

---

src/models.py

fixed to handle Reviews and Additional literature topics properly

fixed to handle non-primary literature topics properly

---

src/models.py

fixed to handle Primary/Other primary tags at the same time properly

fixed to handle Primary/Other primary tags at the same time properly

---

src/views.py

https://redmine.yeastgenome.org/issues/5191

5191 search alias

---

src/js_src/containers/locus/summaries.js
src/js_src/containers/reserve/show.js

https://redmine.yeastgenome.org/issues/5533

Update to read id from props.

---

src/helpers.py
src/loading/load_summaries_sync.py

https://redmine.yeastgenome.org/issues/5391

5391 summary upper case issue

---

src/__init__.py
src/models.py
src/views.py
test/mock_helpers.py

https://redmine.yeastgenome.org/issues/5360

5360 ptm table

---

package.json
src/__init__.py
src/curation_views.py
src/js_src/actions/metaActions.js
src/js_src/constants.js
src/js_src/containers/curateHome/layout.js
src/js_src/containers/layout/index.js
src/js_src/containers/publicHome/index.js
src/js_src/reducers/metaReducer.js

https://redmine.yeastgenome.org/issues/5553

5553 ci alerts

---

src/__init__.py
src/curation_views.py
src/js_src/actions/phenotypeActions.js
src/js_src/containers/curateHome/layout.js
src/js_src/containers/phenotype/autocompleteSection.js
src/js_src/containers/phenotype/commentSection.js
src/js_src/containers/phenotype/conditionSection.js
src/js_src/containers/phenotype/dataList.js
src/js_src/containers/phenotype/edit.js
src/js_src/containers/phenotype/editPhenotype.js
src/js_src/containers/phenotype/new.js
src/js_src/containers/phenotype/newPhenotype.js
src/js_src/containers/phenotype/oneAnnotation.js
src/js_src/containers/phenotype/oneConditionGroup.js
src/js_src/containers/phenotype/pulldownSection.js
src/js_src/containers/phenotype/search.js
src/js_src/containers/phenotype/searchPhenotype.js
src/js_src/containers/phenotype/style.css
src/js_src/containers/phenotype/textFieldSection.js
src/js_src/reducers/index.js
src/js_src/reducers/phenotypeReducer.js
src/js_src/routes.js
src/phenotype_helpers.py

Code for new phenotype curation pages (NEW, SEARCH, EDIT)

Pheno ci 5321

---

scripts/loading/go/gpad_config.py
scripts/loading/go/load_gpad.py
scripts/loading/ontology/disease.py
scripts/loading/ontology/efo.py
scripts/loading/ontology/go.py
scripts/loading/ontology/psimi.py
scripts/loading/util.py
src/models.py

1. adding new gpad file to GO annotation loading pipeline
2. converting underscores to spaces in go qualifiers
3. uploading all gpad files plus gpi file to s3 with sgdid and datestamp

New gpad 5549

---

src/phenotype_helpers.py

1. fixed to give a readable message when a data value is too long
2. added a check to make sure allele is not in the database before inserting even though the allele is not in the autocomplete.

phenotype CI fixes

---

src/__init__.py
src/author_response_helpers.py
src/curation_views.py
src/js_src/containers/authorResponse/process.js
src/js_src/containers/authorResponse/processOneResponse.js
src/js_src/containers/authorResponse/show.js
src/js_src/containers/authorResponse/showAllResponses.js
src/js_src/containers/curateHome/layout.js
src/js_src/containers/litguide/addLitGuide.js
src/js_src/reducers/authorResponseReducer.js
src/js_src/routes.js
src/models.py

Curation interface for author response processing

Submit data 5556

---

src/models.py

https://redmine.yeastgenome.org/issues/5647

Change the loging format from basic.

---

src/models_helpers.py

https://redmine.yeastgenome.org/issues/5554

Use taxid  to find other strain.

---

src/curation_views.py
src/js_src/containers/layout/index.js

https://redmine.yeastgenome.org/issues/5651

5651 ci count

---

src/curation_views.py
src/js_src/components/forms/flexiForm.js
src/js_src/containers/publicHome/index.js

https://redmine.yeastgenome.org/issues/5638

5638 ci login

---

.pytest_cache/v/cache/lastfailed
.travis.yml
Makefile
custom_logger.py
data/www/readme.md
scripts/search/index_elastic_search.py
src/curation_views.py
src/loading/scrapy/pages/spiders/pages_spider.py
src/models.py
test/test_logs/test_log_helpers.py

- Should fix missing logs issue but we need to refactor our entire log setup.
-------
Redmine: #5630

Add log module

---

production.ini
src/curation_helpers.py
src/curation_views.py
src/models.py

https://redmine.yeastgenome.org/issues/5663

5663 curation logs

---

src/curation_views.py

https://redmine.yeastgenome.org/issues/5674
PTM Interface showing unable to add new PTM as it already exists.

5674 ptm duplicate issue

---

scripts/dumping/curation/dump_gff.py
scripts/loading/ontology/__init__.py
scripts/loading/ontology/so.py
src/models.py
system_config/cron/curation_crontab
system_config/cron/s3_copy_files.sh

1. adding/loading term_name to SO table 
2. dumping term_name out to gff file instead of dumping display_name
3. adding new script for copying active files around s3 (sgd-archive and latest)
4. updating crontab

adding term name to SO and others

---

production.ini

https://redmine.yeastgenome.org/issues/5689

add es queries to es.log

---

development.ini
production.ini
requirements.txt

https://redmine.yeastgenome.org/issues/5384

5384 traffic be

---

production.ini

https://redmine.yeastgenome.org/issues/5699

Fix production logs

---

src/js_src/containers/postTraslationModificaition/ptmForm.js

https://redmine.yeastgenome.org/issues/5700
The commits on qa are part of this redmine and PR.
6cae78ce71a1034414e0658b89f8cc89f497af7e
3bae800681dffb4bc7806f7173c0e750d1447735

PTM autocomplte

---

src/__init__.py
src/disease_helpers.py
src/js_src/containers/disease/diseaseForm.js

insert/update has_disease={true/false} if new gene annotation or last annotation deleted

address 'has_disease' value for disease tab

---

src/curation_views.py

https://redmine.yeastgenome.org/issues/5730

5730 ptm encode issue

---

scripts/loading/NISS/extract_sequences.py
scripts/loading/NISS/load_NISS.py
scripts/loading/NISS/proteindomain.py
scripts/loading/NISS/proteindomainannotation.py
scripts/loading/NISS/proteinsequence_detail.py
scripts/loading/NISS/retrieveProtParam.py
scripts/loading/dbxref/update_dbxref.py
src/js_src/components/tagList/index.js
src/litguide_helpers.py
src/models.py

* adding code to handle genes that are not in REF genome
* fixed code to handle external IDs for genes with same protein sequences properly
* adding code to accept complex/pathway as new objects for Lit Triaging/LitGuide TODO CI

NISS; DBXREF; COMPLEX/PATHWAY as new objects 

---

src/models.py

1. fixed the bug in identifying main_strain name for tab display 
2. fixed to make Lit Triaging Tags with gene names work properly

Fixed the seq tab issue + Lit Triage CI

---

api_docs/swagger.json
docs/swagger.json

- Remove schemes so it picks relative protocol(http or https)
- Fix protocol mismatch causing the 301 response

remove schemes

---

src/helpers.py

https://redmine.yeastgenome.org/issues/5776

fix to use the original_word.

---

scripts/search/index_es_7.py
scripts/search/index_variant_data.py
scripts/search/variant_data_mapping.py
src/views.py

- add mapping for variant data index
- modify main es-index script in favor of variant_data index script

5832 search variant bug fix

---

scripts/search/es7_mapping.py
scripts/search/index_es_7.py
scripts/search/index_es_helpers.py
src/search_helpers.py
src/views.py

- add NCBI link for protein
- RM#5838 fix

5702 ncbi maps

---

schema/nex2-annotation-tables.sql
schema/nex2-basic-tables.sql
schema/nex2-constraints.sql
schema/nex2-dbentity-tables.sql
schema/nex2-dbentity-triggers.sql
schema/nex2-grants.sql
schema/nex2-object-tables.sql
schema/nex2-object-triggers.sql
schema/nex2-ontology-tables.sql

schema changes accumulated for some time.

5635 5761 5741 5779 schema

---

schema/nex2-dbentity-tables.sql
schema/nex2-dbentity-triggers.sql

* locus_url.obj_url to 2000; url_type add 'Alliance' 
* add reference_class column and set check constraint
* fix trigger type alias_id to allele_alias_id

minor mods

---

schema/nex2-annotation-triggers.sql
scripts/loading/funccomp/load_funccomp.py
src/__init__.py
src/complement_helpers.py
src/curation_views.py
src/js_src/actions/complementActions.js
src/js_src/containers/complement/complementForm.js
src/js_src/containers/complement/fileUpload.js
src/js_src/containers/complement/index.js
src/js_src/containers/complement/style.css
src/js_src/containers/curateHome/layout.js
src/js_src/reducers/complementReducer.js
src/js_src/reducers/index.js
src/js_src/routes.js
src/models.py
src/models_helpers.py

#5351 - create new table functionalcomplementannotation
#5889 - load data 
#5359 - curator interface

Complement CI

---

src/complement_helpers.py

fix hgnc url

---

src/complement_helpers.py

remove /hgnc in url

---

src/complement_helpers.py

comment optional

---

schema/nex2-constraints.sql
schema/nex2-object-tables.sql
schema/nex2-object-triggers.sql

#5984 move assay_id column/FK/index/trigger to datasetsample

assay_id schema changes

---

schema/nex2-annotation-tables.sql

update go_qualifier redmine #6012

update go_qualifier allowable values and add located in

---

Gemfile
config/deploy.rb

to make deploy work from my laptop have to upgrade capistrano

upgrade capistrano to 3.8 for remote deploy to work on big sur

---

config/deploy.rb
src/disease_helpers.py
src/models.py

with_ortholog is made optinal.
https://redmine.yeastgenome.org/issues/6143

6143 disease CI minor mods

---

scripts/dumping/alliance/affectedGeneModel.py
scripts/dumping/alliance/affectedGeneModelPersistent.py
scripts/dumping/alliance/alleles.py
scripts/dumping/alliance/allelesPersistent.py
scripts/dumping/alliance/basic_gene_information.py
scripts/dumping/alliance/bgiPersistent.py
scripts/dumping/alliance/disease.py
scripts/dumping/alliance/disease_persistent.py
scripts/dumping/alliance/expression.py
scripts/dumping/alliance/htp_datasamples.py
scripts/dumping/alliance/htp_datasets.py
scripts/dumping/alliance/phenotype.py
scripts/dumping/alliance/refs.py
src/data_helpers.py
src/models.py

move to main repo

---

schema/nex2-curation-triggers.sql

Updated deletelog table row to include value for new topic_entity_tag_id column

6516 update deletelog table

---

schema/nex2-curation-triggers.sql

Replace references to old reference_id column to newer pmid column.

6530_AuthorResponse_CI
